"""Explainability layer (§6.2) — reason codes into officer / customer / consent copy.

Every revision carries a reason code; explainability is load-bearing, required
for RBI, DPDP and customer-dispute handling. In production the customer copy is
generated by an LLM against structured templates; here it is deterministic so
the demo is hermetic.
"""
from __future__ import annotations

from dataclasses import dataclass

REASON_TEXT = {
    # intent drivers
    "VELOCITY_RISING": "spend velocity is accelerating",
    "DISCRETIONARY_LIFT": "growth is led by discretionary/aspirational categories",
    "CATEGORY_QUALITY_UP": "spend mix is moving up-market",
    "STABLE_INFLOW": "income inflow is regular and predictable",
    "HEALTHY_BUFFER": "a healthy cash buffer between inflow and outflow",
    "MIN_DUE_DEPENDENCY_RISING": "reliance on paying only the minimum due is rising",
    "ERRATIC_INFLOW": "income inflow has turned irregular",
    "SHRINKING_BUFFER": "the cash buffer is shrinking",
    "HIGH_UTILIZATION": "sustained high utilisation",
    "DECLINES_UNDER_PRESSURE": "high-value declines under liquidity pressure",
    "RECENT_DPD": "recent days-past-due history",
    "VELOCITY_PLUGGING_HOLE": "rising spend appears to be plugging a cash-flow hole",
    "SEASONAL_SPIKE": "a spike concentrated in the festive/seasonal window",
    "HISTORICAL_PREPAYMENT": "a track record of prepaying balances",
    "FESTIVE_CONCENTRATION": "spend concentrated in travel/retail this season",
    "TRADE_CREDIT_DPD": "days-past-due on supplier invoices (trade credit)",
    "PROMOTER_SPEND_VS_MAXED_WORKING_CAPITAL": "promoter spend spiking while the business working-capital line is maxed",
    # knockouts / guardrails
    "KNOCKOUT_FRAUD": "an active fraud / identity-fraud flag",
    "KNOCKOUT_LEGAL_BLOCK": "a legal block or insolvency status",
    "KNOCKOUT_DPD_30_PLUS": "an active 30+ days-past-due",
    "FREQUENCY_GATE": "an increase was already applied within the frequency window",
    "POST_DECREASE_COOLDOWN": "a cooldown is active following a recent risk decrease",
    "LEVERAGE_CEILING": "the per-customer rolling leverage ceiling",
    "PORTFOLIO_VELOCITY_CAP": "the portfolio-level increase-velocity cap",
    "CAPACITY_CAP": "the affordability (capacity) ceiling",
    "INACTIVITY_RIGHTSIZE": "a dormant, undrawn limit right-sized to free capital",
    "NO_CLEAR_INTENT": "no clear directional intent in the latest signals",
}

DIRECTION_VERB = {
    "INCREASE": "increase",
    "DECREASE": "reduce",
    "MAINTAIN": "maintain",
    "FREEZE": "freeze",
}


@dataclass
class ExplainerOutput:
    officer: str
    customer: str
    consent: str  # consent-as-value-lever copy for offers (§6.3)


def _phrase(codes: list[str]) -> str:
    bits = [REASON_TEXT.get(c, c.replace("_", " ").lower()) for c in codes]
    return "; ".join(dict.fromkeys(bits)) if bits else "the latest signals"


def render(
    *,
    direction: str,
    duration: str,
    intent: str,
    tier: int,
    matrix_cell: str,
    current_limit: float,
    recommended_limit: float,
    magnitude_pct: float,
    confidence: float,
    pd_pre: float,
    pd_post: float,
    income_estimate: float,
    reason_codes: list[str],
    applied_caps: list[str],
    pipeline: str,
    auto_revert_days: int | None,
) -> ExplainerOutput:
    drivers = _phrase(reason_codes)
    delta = recommended_limit - current_limit
    dur = " temporary" if duration == "TEMPORARY" else ""
    revert = f" It auto-reverts in {auto_revert_days} days." if auto_revert_days else ""
    caps_clause = f" Bounded by {_phrase(applied_caps)}." if applied_caps else ""

    officer = (
        f"{matrix_cell} → {DIRECTION_VERB[direction].upper()}{dur}. "
        f"Intent: {intent} (conf {confidence:.0%}). "
    )
    if direction in {"INCREASE", "DECREASE"}:
        officer += (
            f"Limit ₹{current_limit:,.0f} → ₹{recommended_limit:,.0f} "
            f"({magnitude_pct:+.1f}%, {'+' if delta>=0 else ''}₹{delta:,.0f}). "
        )
    else:
        officer += f"Holding limit at ₹{current_limit:,.0f}. "
    officer += (
        f"PD {pd_pre:.2%} → {pd_post:.2%}. Income est ₹{income_estimate:,.0f}/mo. "
        f"Drivers: {drivers}.{caps_clause}"
    )
    if pipeline == "OFFER":
        officer += " Consent-gated offer — paused until customer OTP/MPIN approval."

    # Customer-facing copy.
    if pipeline == "OFFER":
        customer = (
            f"You're eligible for a{dur} credit-limit increase to ₹{recommended_limit:,.0f}. "
            f"Approve in-app to activate it.{revert}"
        )
        consent = (
            f"Share your income securely to unlock a higher limit of ₹{recommended_limit:,.0f}. "
            "Approve with OTP/MPIN — you can decline any time."
        )
    elif direction == "DECREASE":
        customer = (
            "We've adjusted your credit limit to better match your recent account activity, "
            "keeping a buffer above your current balance. You can review the details in-app."
        )
        consent = ""
    else:
        customer = "Your credit limit remains unchanged at this time."
        consent = ""

    return ExplainerOutput(officer=officer, customer=customer, consent=consent)
